title: Function Player
description: Official documentation for Function Player - A Unity plugin for visual function execution

# For GitHub Pages native support
remote_theme: just-the-docs/just-the-docs

url: https://guilleatm.github.io/function-player-docs

aux_links:
  "See on Unity Asset Store": "https://assetstore.unity.com/packages/tools/utilities/function-player-329120"
  "Support": "mailto:guillearnautm@gmail.com"

# Enable search functionality
search_enabled: true

# Navigation structure
nav_sort: case_insensitive

# Footer content
footer_content: "Copyright &copy; 2025 Function Player. All rights reserved."

# Color scheme - built-in dark theme
color_scheme: dark

# Enable back to top link
back_to_top: false
# back_to_top_text: "Back to top"

# Enable edit this page link (you can customize this later)
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/guilleatm/function-player-docs"
gh_edit_branch: "main"
gh_edit_source: "/"
gh_edit_view_mode: "tree"

# Plugins
plugins:
  - jekyll-seo-tag
